version: '2'
volumes:
    bundles:
    vimmysettings:
    vundle:
    ultisnips:
services:
    marcvimbuilder:
        build: machine
        volumes:
          - ./build:/opt/build
          - bundles:/opt/clone
          - vimmysettings:/opt/clone_vimmysettings
          - vundle:/opt/clone_vundle
          - ultisnips:/opt/clone_UltiSnips

