version: '2'
services:
    marcvimbuilder:
        build: machine
        volumes:
          - ./build:/build

    testvim:
        env_file: ./testvim/env
        volumes:
          - ./build:/build
        build:
          context: ./testvim
          dockerfile: dummy

    testvim_16.04:
        extends: testvim
        build:
          dockerfile: Dockerfile_16.04
    testvim_14.04:
        extends: testvim
        build:
          dockerfile: Dockerfile_14.04
