version: '2'
services:
    builder:
        build: machine
        volumes:
          - ~/.vim/UltiSnips:/home/vide/.vim/UltiSnips
        command: /start.sh
        environment:
            - ODOO_HOME
