version: '3.3'
services:
    vide:
        privileged: true
        build: .
        working_dir: $CURRENT_DIR
        volumes:
          - ./UltiSnips:/home/vide/.vim/UltiSnips
          - ./vim-my-settings:/home/vide/.vim/bundle/vim-my-settings
          - ./installed_plugins/vim-openerp-browser:/home/vide/.vim/bundle/vim-openerp-browser
          - ~/.config/vide/cache:/home/vide/.cache
          - ./files/vimrc:/home/vide/.config/nvim/init.vim
          - $HOME:$HOME
          - $CURRENT_DIR_HOST:$CURRENT_DIR
            # - ~/development/vim-openerp-browser:/home/vide/.vim/bundle/vim-openerp-browser
            #- ~/development/vim-run-file:/home/vide/.vim/bundle/vim-run-file
        environment:
            - LOCAL_UID=$LOCAL_UID
            - GIT_DISCOVERY_ACROSS_FILESYSTEM=1
