version: '2'
services:
    marcvimbuilder:
        build: machine
        volumes:
          - ./build:/build
networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
            driver: default
            config:
                - subnet: 10.15.30.0/24
                  gateway: 10.15.30.1
