version: '3.3'
services:
    vide:
        build: .
        volumes:
          - ./UltiSnips:/home/vide/.vim/UltiSnips
          - ./vim-my-settings:/home/vide/.vim/bundle/vim-my-settings
          - ~/.config/vide/cache:/home/vide/.cache
          - ./files/vimrc:/home/vide/.config/nvim/init.vim
            # - ~/development/vim-openerp-browser:/home/vide/.vim/bundle/vim-openerp-browser
            #- ~/development/vim-run-file:/home/vide/.vim/bundle/vim-run-file
        environment:
            - ODOO_HOME
