#!/bin/bash
#docker-compose build
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
rm /usr/local/bin/vide 2>/dev/null 1>&2 || true
ln -s "$DIR/vide" /usr/local/bin/vide

cat<<EOF
Extend the vide configuration for your needs:

~/.vide
---------------------

version: '3.3'
services:
    vide:
        environment:
            - ODOO_HOME=/opt/odoo
        volumes:
            - /opt/odoo:/opt/odoo
EOF
