#!/usr/bin/env python
import os
import sys
import inspect
import subprocess

parameters = sys.argv[1:]
args = [x for x in parameters if x.startswith('-')]
parameters = [x for x in parameters if not x.startswith('-')]

SUDO = ['-sudo' in args]

filepath = inspect.getfile(inspect.currentframe())
dir = os.path.dirname(os.path.join(os.path.dirname(filepath), os.path.realpath(filepath)))
cwd = os.getcwd()

if len(parameters) > 1:
    print("Only 1 parameter supported")
    sys.exit(0)

FILE = parameters[0] if parameters else ""

if not FILE:
    CURRENT_DIR = cwd
else:
    # converts relative path to absolute path
    FILE = os.path.join(os.path.dirname(FILE), os.path.realpath(FILE))
    if os.path.isdir(FILE):
        CURRENT_DIR = FILE
    else:
        CURRENT_DIR = os.path.dirname(FILE)

CURRENT_DIR = os.path.join(os.path.dirname(CURRENT_DIR), os.path.realpath(CURRENT_DIR))

APPENDIX = ""
for folder in [
        '/etc',
        '/var',
        '/run',
        '/tmp'
]:
    if CURRENT_DIR.startswith(folder) and not CURRENT_DIR.startswith(folder + "/"):
        APPENDIX = "_"
        FILE = folder + APPENDIX + '/' + FILE[len(folder):]

subprocess.Popen([
    'docker-compose',
    'run',
    '--rm',
    '--workdir={}'.format(CURRENT_DIR),
    os.path.expandvars('--volume=$HOME:$HOME'),
    '--volume={CURRENT_DIR}:{CURRENT_DIR}{APPENDIX}'.format(**locals()),
    '-e LOCAL_UID={}'.format(os.getuid() if not SUDO else 0),
    'vide',
    '/start.sh',
    FILE
], cwd=dir).wait()
