FROM ubuntu:16.04

RUN apt-get update 
RUN apt-get install -y ctags inotify-tools npm nodejs
RUN apt-get install -y git
RUN apt-get install -y iputils-ping
RUN apt-get install -y vim-nox-py2

RUN npm install -g jshint

CMD while true; do sleep 10; done;
