FROM ubuntu:14.04

RUN apt-get update 
RUN apt-get install -y ctags inotify-tools npm nodejs
RUN npm install -g jshint
RUN apt-get install -y git
RUN apt-get install -y iputils-ping
RUN apt-get install -y vim


CMD while true; do sleep 10; done;
