#!/bin/bash

apt-get install -y vim psycopg2 python-pip

# for fuser command to kill openerp
apt-get install -y psmisc lsof

# syntastic checker
npm install -g jshint
pip install flake8
apt-get install -y libxml2-utils

# install silver surfer 0.30.0
git clone --branch 0.30.0 https://github.com/ggreer/the_silver_searcher /tmp/ag1
cd /tmp/ag1
./build.sh
sudo make install

#
echo Setting git to remember passwords
git config credential.helper store
