#!/bin/bash
echo "Extracting file into /tmp"

echo "Installing for $(whoami)"

# searches for the line number where finish the script and start the tar.gz
SKIP=`awk '/^__TARFILE_FOLLOWS__/ { print NR + 1; exit 0; }' $0`
#remember our file name
THIS=`pwd`/$0

# take the tarfile and pipe it into tar
mkdir /tmp/vimmy
tail -n +$SKIP $THIS | tar -xz -C /tmp/vimmy
cd /tmp/vimmy

echo copying vim to local folder
rsync /tmp/vimmy/.vim ~/ -ar 
rsync /tmp/vimmy/.vimrc ~/ -ar 

echo copying vim to system dir
cp /tmp/vimmy/vim /usr/bin

rm -Rf /tmp/vimmy

echo "Adding cronjob to update vim packages"
#if [ ! $(grep -q vimupdate ~/.bashrc) ]; then
	echo '~/.vimupdate &' >> ~/.bashrc
#fi


# Any script here will happen after the tar file extract.
echo "Finished"
exit 0
# NOTE: Don't place any newline characters after the last line below.
__TARFILE_FOLLOWS__
