#!/bin/bash
echo install vim
set -xe

vim +PluginInstall +qall
echo Doing second round
sleep 3
vim +PluginInstall +qall

echo In future do updates with :PluginUpdate
echo List your Plugins with :PluginList
