#!/bin/bash
echo compiling YouCompleteMe
set -xe

cd /opt/clone/YouCompleteMe
# tern-complete=javascript support, needs nodejs and npm
/usr/bin/python install.py --tern-completer

echo In future do updates with :PluginUpdate
echo List your Plugins with :PluginList
