#!/bin/bash
set -e
echo "Extracting marcvim into /tmp"
echo "Installing marcvim for $(whoami)"

# searches for the line number where finish the script and start the tar.gz
SKIP=`awk '/^__TARFILE_FOLLOWS__/ { print NR + 1; exit 0; }' $0`
#remember our file name
DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
SCRIPTNAME=$(basename $(readlink -nf $0))

# take the tarfile and pipe it into tar
rm -Rf /tmp/vimmy || true
mkdir /tmp/vimmy
tail -n +$SKIP $DIR/$SCRIPTNAME | tar -xz -C /tmp/vimmy
cd /tmp/vimmy

echo copying vim to local folder
rsync /tmp/vimmy/.vim-my-settings ~/ -arl
rsync /tmp/vimmy/.vimupdate ~/ -aP && chmod a+x ~/.vimupdate
rsync /tmp/vimmy/gitwatch.sh ~/ -aP && chmod a+x ~/gitwatch.sh

cd ~
rm -Rf .vim &>/dev/null || true
rm -Rf .vimrc &>/dev/null || true
ln -s .vim-my-settings/.vim
ln -s .vim-my-settings/plugins/vim-my-settings/.vimrc

echo copying vim to home dir
cp /tmp/vimmy/vim ~/vim

rm -Rf /tmp/vimmy

echo "Adding cronjob to update vim packages"
if [ ! $(grep -q vimupdate ~/.bashrc) ]; then
	echo '~/.vimupdate &' >> ~/.bashrc
fi

# compile youcompleteme for the platform
# tern-complete=javascript support, needs nodejs and npm
# cd ~/.vim/bundle/YouCompleteMe/ && python install.py --tern-complete
echo 'cd ~/.vim/bundle/YouCompleteMe/ && python install.py --tern-complete' > ~/vim-compile-youcompleteme
chmod a+x ~/vim-compile-youcompleteme

# install dependencies
apt-get install -y ctags nodejs npm
update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10
npm install -g jshint

#silver surfer
which ag || {
    apt-get install -y automake pkg-config liblzma-dev libpcre3-dev
    if [[ -d /tmp/ag ]]; then
        rm -Rf /tmp/ag
    fi
    git clone https://github.com/ggreer/the_silver_searcher /tmp/ag && cd /tmp/ag && ./build.sh && make install
}

echo "Finished"
exit 0
# NOTE: Don't place any newline characters after the last line below.
__TARFILE_FOLLOWS__
