#!/bin/bash
set -e
set -x
echo "Extracting marcvim into /tmp"
echo "Installing marcvim for $(whoami)"

# searches for the line number where finish the script and start the tar.gz
SKIP=`awk '/^__TARFILE_FOLLOWS__/ { print NR + 1; exit 0; }' $0`
#remember our file name
DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
SCRIPTNAME=$(basename $(readlink -nf $0))

# take the tarfile and pipe it into tar
rm -Rf /tmp/vimmy || true
mkdir /tmp/vimmy
tail -n +$SKIP $DIR/$SCRIPTNAME | tar -xz -C /tmp/vimmy
cd /tmp/vimmy

echo copying vim to local folder
rm -Rf ~/.vim &>/dev/null || true
mv /tmp/vimmy/.vim ~/.vim
rsync /tmp/vimmy/.vimupdate ~/ -aP && chmod a+x ~/.vimupdate
rsync /tmp/vimmy/gitwatch.sh ~/ -aP && chmod a+x ~/gitwatch.sh

rm -Rf .vimrc &>/dev/null || true
ln -s .vim-my-settings/plugins/vim-my-settings/.vimrc ~/.vimrc

rm -Rf /tmp/vimmy
cd ~ # hint nodejs requires cwd

echo "Adding cronjob to update vim packages"
if [ ! $(grep -q vimupdate ~/.bashrc) ]; then
	echo '~/.vimupdate &' >> ~/.bashrc
fi

# compile youcompleteme for the platform
# tern-complete=javascript support, needs nodejs and npm
# cd ~/.vim/bundle/YouCompleteMe/ && python install.py --tern-complete
echo 'cd ~/.vim/bundle/YouCompleteMe/ && python install.py --tern-complete' > ~/vim-compile-youcompleteme
chmod a+x ~/vim-compile-youcompleteme

# install dependencies
if ping -c 1 8.8.8.8; then
    apt-get install -y ctags nodejs npm
    update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10
    npm install -g jshint
fi

#silver surfer
which ag || {
    if ping -c 1 8.8.8.8; then
        apt-get install -y automake pkg-config liblzma-dev libpcre3-dev
        if [[ -d /tmp/ag ]]; then
            rm -Rf /tmp/ag
        fi
        git clone --depth 1 --branch master https://github.com/ggreer/the_silver_searcher /tmp/ag && cd /tmp/ag && ./build.sh && make install
    fi
}

echo "Finished"
exit 0
# NOTE: Don't place any newline characters after the last line below.
__TARFILE_FOLLOWS__
