#!/bin/bash
echo install vim
set -xe
rm ~/.vimrc || true
rm -Rf ~/.vim ~/.vim-my-settings || true
mkdir -p ~/.vim-my-settings/plugins
cd ~/.vim-my-settings/plugins
git clone --depth 1 https://github.com/marcwimmer/vim-my-settings.git
ls -lha vim-my-settings/
cd 
echo Setting the initial .vimrc
ln -s .vim-my-settings/plugins/vim-my-settings/.vimrc
ln -s .vim-my-settings/.vim

echo "setting up vundle, see: https://github.com/gmarik/Vundle.vim"
git clone --depth 1 https://github.com/gmarik/Vundle.vim.git ~/.vim-my-settings/.vim/bundle/Vundle.vim

echo "install bundles manually from bundles.list"
BUNDLELIST=~/.vim-my-settings/plugins/vim-my-settings/bundles.list
ls -lha $BUNDLELIST
cat $BUNDLELIST

while read bundle
do
    echo cloning bundle $bundle
    if [ -z $bundle ]; then
        continue
    fi

    echo $bundle |grep -q "^#" && continue
    cd ~/.vim/bundle
    for i in 1 2 3 4 5 6 7 8 9 10;
    do 
        git clone --depth 1 --recursive https://github.com/$bundle && break
        sleep 15
    done
done<$BUNDLELIST

